"""Typed contracts for the generic PDF package validator."""

from validibot_shared.pdf.envelopes import (
    PDF_INVENTORY_SCHEMA_VERSION,
    PdfCollection,
    PdfCollectionField,
    PdfDeclaration,
    PdfDocumentFacts,
    PdfExtension,
    PdfInputEnvelope,
    PdfInputs,
    PdfInventory,
    PdfInventorySource,
    PdfLogicalStructureFacts,
    PdfMember,
    PdfOutputEnvelope,
    PdfOutputs,
    PdfParserInfo,
    PdfPayloadSelector,
    PdfProcessingLimits,
    PdfRequirement,
    PdfRichMediaAnnotation,
    PdfSignature,
    PdfThreeDAnnotation,
)

__all__ = [
    "PDF_INVENTORY_SCHEMA_VERSION",
    "PdfCollection",
    "PdfCollectionField",
    "PdfDeclaration",
    "PdfDocumentFacts",
    "PdfExtension",
    "PdfInputEnvelope",
    "PdfInputs",
    "PdfInventory",
    "PdfInventorySource",
    "PdfLogicalStructureFacts",
    "PdfMember",
    "PdfOutputEnvelope",
    "PdfOutputs",
    "PdfParserInfo",
    "PdfPayloadSelector",
    "PdfProcessingLimits",
    "PdfRequirement",
    "PdfRichMediaAnnotation",
    "PdfSignature",
    "PdfThreeDAnnotation",
]
